-- MySQL Script generated by MySQL Workbench
-- Sun Dec 10 17:18:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Spotters
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Spotters` ;

-- -----------------------------------------------------
-- Schema Spotters
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Spotters` DEFAULT CHARACTER SET utf8 ;
USE `Spotters` ;

-- -----------------------------------------------------
-- Table `Spotters`.`AEROPUERTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotters`.`AEROPUERTOS` ;

CREATE TABLE IF NOT EXISTS `Spotters`.`AEROPUERTOS` (
  `idAEROPUERTOS` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(45) NULL,
  `civil/militar` VARCHAR(45) NULL,
  PRIMARY KEY (`idAEROPUERTOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotters`.`AVIONES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotters`.`AVIONES` ;

CREATE TABLE IF NOT EXISTS `Spotters`.`AVIONES` (
  `idAVION` INT NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `alcance` VARCHAR(45) NULL,
  `idAEROPUERTOS` VARCHAR(45) NULL,
  `imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idAVION`),
  CONSTRAINT `idAEROPUERTOS`
    FOREIGN KEY ()
    REFERENCES `Spotters`.`AEROPUERTOS` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotters`.`USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotters`.`USUARIOS` ;

CREATE TABLE IF NOT EXISTS `Spotters`.`USUARIOS` (
  `nombreUSUARIOS` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`nombreUSUARIOS`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
